apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: default
data:
  WEBLATE_SITE_TITLE: Weblate
  WEBLATE_ALLOWED_HOSTS: translate.blockstory.net,*
  WEBLATE_TIME_ZONE: America/Chicago
  WEBLATE_LOGLEVEL: DEBUG
  WEBLATE_REGISTRATION_OPEN: "1"
  WEBLATE_DEBUG: "0"
  WEBLATE_SITE_DOMAIN: translate.blockstory.net
  CELERY_MAIN_OPTIONS: "--pool=gevent"
  CELERY_NOTIFY_OPTIONS: "--pool=gevent"
  CELERY_TRANSLATE_OPTIONS: "--pool=gevent"
  CELERY_MEMORY_OPTIONS: "--pool=gevent"
  CELERY_BACKUP_OPTIONS: "--pool=gevent"
  UWSGI_WORKERS: "1"
  UWSGI_PLUGINS: "ugreen"
  UWSGI_ASYNC: "30"
  UWSGI_UGREEN: "true"