apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: default
data:
  WEBLATE_SITE_TITLE: Weblate
  WEBLATE_ALLOWED_HOSTS: translate.blockstory.net,*
  WEBLATE_TIME_ZONE: America/Chicago
  WEBLATE_LOGLEVEL: DEBUG
  WEBLATE_REGISTRATION_OPEN: "1"
  WEBLATE_DEBUG: "0"

