apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
    spec:
      containers:
      - image: "postgres:10-alpine"
        name: postgres
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_DB
          value: weblate
        - name: POSTGRES_USER
          value: weblate
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: docker-postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: docker-postgres-data
        persistentVolumeClaim:
          claimName: docker-postgres-data

status: {}
