apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: weblate-data
  name: weblate-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
status: {}
